#!/bin/bash
echo "shell file running.."
pkill -f "/usr/local/bin/nodemon start API.js"
PORT=3005
PID=$(lsof -i:$PORT | awk 'NR==2{print $2}');
if [ ! -z "$PID" ]; then
  kill -9 $PID
  echo "$PID KILLED"
fi
nodemon start API.js