#!/bin/bash
echo "fast shell file running.."
pkill -f "/usr/local/bin/nodemon start fast.js"
PORT=3000
PID=$(lsof -i:$PORT | awk 'NR==2{print $2}');
if [ ! -z "$PID" ]; then
  kill -9 $PID
  echo "$PID KILLED"
fi
nodemon start fast.js